### ISSUE TITLE
New chats for every new connection?

### ISSUE THREAD

**Issue by IamKO** [henry-richard7/TeleRAT#6]
Hello, i am interested if i have more than 1 slave, how will it be going? it will create every time new chat? or there will be all one chat but i will have some ID of slave computers? and it does not have an autorun yes? if the computer will be turned off connection will be lost? and connection will be alive untill computer will be turned off or it has some limits, for example, will be turned of after 1 hour of inactivity?

**Comment by henry-richard7** [comment]
Hi, currently i have not tested in multiple slaves, it has no autorun, if the computer shuts down the connection 
is not kept alive but it can be made possible if u can move the file to startup and the connection will be alive till the computer is turned on!.

**Comment by IamKO** [comment]
and connection will be alive untill computer will be turned off or it has some limits, for example, will be turned of after 1 hour of inactivity?

**Comment by henry-richard7** [comment]
It has no limits the connection will be alive as long as the computer is on!

**Comment by IamKO** [comment]
thank you for the quick answer would be great if will improve for several slaves not only one

**Comment by henry-richard7** [comment]
I will work on that thanks!
